apiVersion: v1
kind: Pod
metadata:
  name: pod-3.1
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  containers:
  - name: main-container
    image: nginx
    ports:
    - containerPort: 80
