apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-applicationset
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/SergeyHudinskiy/argocd.git
        revision: main
        directories:
          - path: apps/*
  template:
    metadata:
      name: "{{ path.basename }}"
      labels:
        app: "{{ path.basename }}"
    spec:
      project: default
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
      source:
        repoURL: https://github.com/SergeyHudinskiy/argocd.git
        targetRevision: main
        path: "{{ path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
          - key: app
            operator: In
            values:
              - app1
              - app3
        - matchExpressions:
          - key: app
            operator: In
            values:
              - app2
