apiVersion: v1
kind: Pod
metadata:
  name: pod-1.1
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  containers:
  - name: main-container
    image: nginx
    ports:
    - containerPort: 80
